src/DeinonychusCowboy/TimeTrackerBundle/Entity/IntrinsicColor.php
<?php


namespace DeinonychusCowboy\TimeTrackerBundle\Entity;

use DeinonychusCowboy\TimeTrackerBundle\Lib\Helper;

abstract class IntrinsicColor
{
	private   $hash;
	protected $colorSeed;

	protected abstract function setColorSeed();

	private function getColorInternal()
	{
		if($this->colorSeed === null)
		{
			$this->setColorSeed();
			if($this->colorSeed === null)
			{
				throw new \Exception("Seed not Set!");
			}
		}
		if($this->hash === null)
		{
			$this->hash = Helper::generateHash($this->colorSeed);
		}
	}

	public function getMainColor()
	{
		$this->getColorInternal();

		return Helper::getMainColor($this->hash);
	}

	public function getLightColor()
	{
		$this->getColorInternal();

		return Helper::getLightColor($this->hash);
	}

	public function getPastelColor()
	{
		$this->getColorInternal();

		return Helper::getPastelColor($this->hash);
	}
}

src/DeinonychusCowboy/TimeTrackerBundle/Entity/Task.php
<?php

namespace DeinonychusCowboy\TimeTrackerBundle\Entity;

use DeinonychusCowboy\TimeTrackerBundle\Controller\DefaultController;
use DeinonychusCowboy\TimeTrackerBundle\Lib\DataManager;
use DeinonychusCowboy\TimeTrackerBundle\Lib\Helper;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Table;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinTable;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\OneToMany;
use Doctrine\ORM\PersistentCollection;

/**
 * @Entity
 * @Table(name="Tasks")
 */
class Task implements Identifiable
{
	/**
	 * @var string
	 * @Column(type="string")
	 * @Id
	 */
	private $id;
	/**
	 * @var PersistentCollection
	 * @OneToMany(targetEntity="Interval",mappedBy="task")
	 */
	private $intervals;
	/**
	 * @var int
	 * @Column(type="integer",nullable=true)
	 */
	private $closed;
	/**
	 * @var string
	 * @Column(type="string")
	 */
	private $name;
	/**
	 * @var string
	 * @Column(type="string",nullable=true)
	 */
	private $desc;
	/**
	 * @var PersistentCollection
	 * @ManyToMany(targetEntity="Tag",inversedBy="tasks")
	 * @JoinTable(name="RelTagsTasks")
	 */
	private $tags;

	private function __construct()
	{
	}

	public static function create($name = null,$desc = null)
	{
		$instance       = new self();
		$id             = "T" . Helper::generateId();
		$instance->id   = $id;
		$instance->name = $name
			?: $id;
		$instance->desc = $desc;

		$instance->tags      = new ArrayCollection();
		$instance->intervals = new ArrayCollection();
		$instance->closed    = null;
		DataManager::store($instance);
		DataManager::serialize($id);
		DataManager::commit();
		DataManager::flush($instance);
		unset($instance);

		return DataManager::findById($id);
	}

	public function start()
	{
		if($this->isRunning())
		{
			throw new \Exception("Attempt to start a task that is already running.");
		}
		if($this->closed)
		{
			throw new \Exception("Attempt to start a task that has been closed.");
		}
		$interval = Interval::create();
		$this->intervals->add($interval);
		$interval->setTask($this);
	}

	public function close($note)
	{
		if($this->isRunning())
		{
			throw new \Exception("Attempt to close a task that is running.");
		}
		$this->desc .= "\n\n" . $note;
		$this->closed = time();
	}

	public function addTag($id)
	{
		$tag = DataManager::findById($id);
		$this->tags->add($tag);
		$tag->addObjectRef($this);
	}

	public function removeTag($id)
	{
		$tag = DataManager::findById($id);
		$tag->removeObjectRef($this->getId());
		$this->tags->removeElement($tag);
	}

	public function getId()
	{
		return $this->id;
	}

	/**
	 * @return string
	 */
	public function getDesc()
	{
		return $this->desc;
	}

	/**
	 * @return array
	 */
	public function getIntervals()
	{
		return $this->intervals;
	}

	/**
	 * @return string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * @return boolean
	 */
	public function isRunning()
	{
		return $this->getRunningInterval() !== null;
	}

	public function getRunningInterval()
	{
		foreach($this->intervals->getValues() as $interval)
		{
			if($interval->getStop() === null)
			{
				return $interval;
			}
		}

		return null;
	}

	public function getLastInterval()
	{
		$start = date_create("@0");
		$which = null;
		foreach($this->intervals->getValues() as $interval)
		{
			if($interval->getStart() > $start)
			{
				$start = $interval->getStart();
				$which = $interval;
			}
		}

		return $which;
	}

	public function getTime()
	{
		$total   = $this->getUnixtime();
		$seconds = $total % 60;
		$total -= $seconds;
		$total /= 60;
		$minutes = $total % 60;
		$total -= $minutes;
		$total /= 60;
		$hours = $total % DefaultController::getCurrentUser()->getDayLength();
		$total -= $hours;
		$total /= DefaultController::getCurrentUser()->getDayLength();
		$workdays = $total;

		return new \DateInterval("P" . $workdays . "DT" . $hours . "H" . $minutes . "M" . $seconds . "S");
	}

	public function getUnixtime()
	{
		$total = 0;
		foreach($this->intervals->getValues() as $interval)
		{
			$total += $interval->getSeconds();
		}

		return $total;
	}

	/**
	 * @return boolean
	 */
	public function isClosed()
	{
		return $this->closed !== null;
	}

	public function getCloseUnixtime()
	{
		return $this->closed;
	}

	public function getTags()
	{
		$arr = $this->tags->getValues();
		$ret = array();
		foreach($arr as $obj)
		{
			$ret[$obj->getId()] = $obj;
		}

		return $ret;
	}

	/**
	 * @return array
	 */
	public function getTagIds()
	{
		$arr = array();
		foreach($this->getTags() as $tag)
		{
			$arr[] = $tag->getId();
		}

		return $arr;
	}

	public function setTagIds($ids)
	{
		$tags = $this->getTags();
		foreach($ids as $id)
		{
			if(!array_key_exists($id,$tags))
			{
				$this->addTag($id);
			}
		}
		foreach(array_keys($tags) as $id)
		{
			if(!in_array($id,$ids))
			{
				$this->removeTag($id);
			}
		}
	}

	public function getStatus()
	{
		if($this->isRunning())
		{
			return "RUNNING";
		}
		elseif($this->closed !== null)
		{
			return "CLOSED";
		}
		elseif(count($this->intervals) === 0)
		{
			return "TODO";
		}
		else
		{
			return "OPEN";
		}
		// TODO if has dependencies, blocked
	}

	/**
	 * @param boolean $closed
	 */
	public function setClosed($closed)
	{
		$this->closed = $closed
			? time()
			: null;
	}

	/**
	 * @param mixed $desc
	 */
	public function setDesc($desc)
	{
		$this->desc = $desc;
	}

	/**
	 * @param mixed $name
	 */
	public function setName($name)
	{
		$this->name = $name;
	}
}

src/DeinonychusCowboy/TimeTrackerBundle/Controller/DefaultController.php
<?php

namespace DeinonychusCowboy\TimeTrackerBundle\Controller;

use DeinonychusCowboy\TimeTrackerBundle\Entity\Interval;
use DeinonychusCowboy\TimeTrackerBundle\Entity\IntervalForm;
use DeinonychusCowboy\TimeTrackerBundle\Entity\Tag;
use DeinonychusCowboy\TimeTrackerBundle\Entity\TagForm;
use DeinonychusCowboy\TimeTrackerBundle\Entity\TagGroup;
use DeinonychusCowboy\TimeTrackerBundle\Entity\TagGroupForm;
use DeinonychusCowboy\TimeTrackerBundle\Entity\Task;
use DeinonychusCowboy\TimeTrackerBundle\Entity\User;
use DeinonychusCowboy\TimeTrackerBundle\Lib\DataManager;
use DeinonychusCowboy\TimeTrackerBundle\Entity\TaskForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
	private static $user;

	/**
	 * @return mixed
	 */
	public static function getCurrentUser()
	{
		return self::$user;
	}

	public function init($doctrine)
	{
		self::$user = new User();
		date_default_timezone_set(self::getCurrentUser()->getTimezone());
		DataManager::init($doctrine);
	}

	public function shutdown()
	{
		DataManager::serializeAll();
		DataManager::commit();
	}

	/**
	 * @Route("/")
	 * @Template()
	 */
	public function indexAction(Request $request)
	{
		return $this->redirect("tasklist");
	}

	/**
	 * @Route("/tasklist")
	 * @Template()
	 */
	public function tasklistAction(Request $request)
	{
		$this->init($this->getDoctrine());
		$limit = 30;
		$tasks = array();
		if($request->query->has("all"))
		{
			$tasks = DataManager::getAllTasks($limit);
		}
		else
		{
			$tasks = DataManager::getAllOpenTasks($limit);
		}

		$filter = $request->query->getAlnum("filter");
		if($request->query->has("filter") && !empty($filter))
		{
			$tasks = DataManager::filterWithTag($tasks,$filter);
		}

		return $this->finalize(
			array(
				"user"       => self::getCurrentUser(),
				"filter"     => $request->query->get("filter"),
				"tasks"      => $tasks,
				"tags"       => DataManager::getAllTags(),
				"tag_groups" => DataManager::getAllTagGroups()
			)
		);
	}

	/**
	 * @Route("/raw")
	 * @Template()
	 */
	public function rawlistAction(Request $request)
	{
		$this->init($this->getDoctrine());
		$tasks = DataManager::getAllOpenTasks();

		return $this->finalize(
			array(
				"user"  => self::getCurrentUser(),
				"tasks" => $tasks,
				"tags"  => DataManager::getAllTags(),
			)
		);
	}

	/**
	 * @Route("/taglist")
	 * @Template()
	 */
	public function taglistAction(Request $request)
	{
		$this->init($this->getDoctrine());
		$tags      = DataManager::getAllTags();
		$taggroups = DataManager::getAllTagGroups();

		// TODO show usage count
		return $this->finalize(
			array(
				"user"       => self::getCurrentUser(),
				"tags"       => $tags,
				"tag_groups" => $taggroups,
			)
		);
	}

	/**
	 * @Route("/intervallist")
	 * @Template()
	 */
	public function intervallistAction(Request $request)
	{
		$this->init($this->getDoctrine());
		$intervals = DataManager::getAllIntervals();

		$filter = $request->query->getAlnum("filter");
		if($request->query->has("filter") && !empty($filter))
		{
			$intervals = DataManager::filterWithTag(
				$intervals,
				$request->query->getAlnum("filter"),
				function ($interval)
				{
					return $interval->getTask();
				}
			);
		}

		// TODO show usage count
		return $this->finalize(
			array(
				"user"       => self::getCurrentUser(),
				"tags"       => DataManager::getAllTags(),
				"tag_groups" => DataManager::getAllTagGroups(),
				"intervals"  => $intervals,
				"filter"     => $request->query->getAlnum("filter"),
			)
		);
	}

	private function formAction(Request $request,$callableNewForm,$callableNewObject)
	{
		$form = null;
		$new  = true;
		$obj  = null;
		if($request->query->has("id"))
		{
			$obj  = DataManager::findById($request->query->getAlnum("id"));
			$form = $this->createForm($callableNewForm($obj,0),$obj);
			$new  = false;
		}
		else if($request->getMethod() === "POST")
		{
			$obj  = $callableNewObject();
			$form = $this->createForm($callableNewForm($obj,1),$obj);
		}
		else
		{
			$form = $this->createForm($callableNewForm(null,2),null);
		}

		if($request->getMethod() === "POST")
		{
			$form->handleRequest($request);

			if($form->isValid())
			{
				return $this->finalize(
					null,
					"tasklist" . ($request->query->has("filter")
						? "?filter=" . $request->query->getAlnum("filter")
						: "")
				);
			}
		}

		return array(
			"user"   => self::getCurrentUser(),
			"id"     => $new
				? null
				: $request->query->getAlnum("id"),
			"filter" => $request->query->getAlnum("filter"),
			"form"   => $form->createView(),
			"tags"   => DataManager::getAllTags(),
			"new"    => $new,
			"obj"    => $obj,
		);
	}

	/**
	 * @Route("/task")
	 * @Template()
	 */
	public function taskAction(Request $request)
	{
		$this->init($this->getDoctrine());

		return $this->finalize(
			$this->formAction(
				$request,
				function ($task,$state) use ($request)
				{
					$form = new TaskForm(
						$state == 2
							? $request->query->getAlnum('filter')
							: null
					);
					$form->setClosed(
						$task !== null
							? $task->isClosed()
							: false
					);

					return $form;
				},
				function ()
				{
					return Task::create();
				}
			)
		);
	}

	/**
	 * @Route("/tag")
	 * @Template()
	 */
	public function tagAction(Request $request)
	{
		$this->init($this->getDoctrine());

		return $this->finalize(
			$this->formAction(
				$request,
				function ($tag)
				{
					return new TagForm();
				},
				function ()
				{
					return Tag::create();
				}
			)
		);
	}

	/**
	 * @Route("/taggroup")
	 * @Template()
	 */
	public function tagGroupAction(Request $request)
	{
		$this->init($this->getDoctrine());

		return $this->finalize(
			$this->formAction(
				$request,
				function ($taggroup)
				{
					return new TagGroupForm();
				},
				function ()
				{
					return TagGroup::create();
				}
			)
		);
	}

	/**
	 * @Route("/interval")
	 * @Template()
	 */
	public function intervalAction(Request $request)
	{
		$this->init($this->getDoctrine());
		if($request->query->has("id"))
		{
			$interval = DataManager::findById($request->query->getAlnum("id"));
			if($interval->getStop() === null)
			{
				$interval->setStop(date_create());
			}
		}

		return $this->finalize(
			$this->formAction(
				$request,
				function ($interval)
				{
					return new IntervalForm();
				},
				function ()
				{
					return null; // created from Task
				}
			)
		);
	}

	private function finalize($return,$redirect = null)
	{
		$this->shutdown();
		if($redirect !== null)
		{
			return $this->redirect($redirect);
		}

		return $return;
	}

	/**
	 * @Route("/taskstart")
	 * @Template()
	 */
	public function taskStartAction(Request $request)
	{
		$this->init($this->getDoctrine());
		if($request->query->has("id"))
		{
			$task = DataManager::findById($request->query->getAlnum("id"));
			$task->start();
		}

		return $this->finalize(
			array("user" => self::getCurrentUser(),"filter" => $request->query->getAlnum("filter")),
			"tasklist" . ($request->query->has("filter")
				? "?filter=" . $request->query->getAlnum("filter")
				: "")
		);
	}

	/**
	 * @Route("/taskstop")
	 * @Template()
	 */
	public function taskStopAction(Request $request)
	{
		$this->init($this->getDoctrine());
		if($request->query->has("id"))
		{
			$task = DataManager::findById($request->query->getAlnum("id"));

			return $this->finalize(
				null,
				"interval?id=" . $task->getRunningInterval()->getId() . ($request->query->has("filter")
					? "&filter=" . $request->query->getAlnum("filter")
					: "")
			);
		}

		return $this->finalize(
			array("user" => self::getCurrentUser(),"filter" => $request->query->getAlnum("filter")),
			"tasklist" . ($request->query->has("filter")
				? "?filter=" . $request->query->getAlnum("filter")
				: "")
		);
	}

	/**
	 * @Route("/report")
	 * @Template()
	 */
	public function reportAction(Request $request)
	{
		$this->init($this->getDoctrine());
		$tags        = DataManager::getAllTags();
		$closedTasks = DataManager::getAllClosedTasks();
		$period      = time();
		// find earliest close date
		foreach($closedTasks as $task)
		{
			$period = $task->getCloseUnixtime() < $period
				? $task->getCloseUnixtime()
				: $period;
		}
		// sort tasks by date
		uasort(
			$closedTasks,
			function ($a,$b)
			{
				return $a->getCloseUnixtime() - $b->getCloseUnixtime();
			}
		);
		$countClosedTasksPayload = array();
		// calculate amounts for each tag
		foreach($tags as $tag)
		{
			$tagTasks        = DataManager::filterWithTag($closedTasks,$tag->getId());
			$tagColor        = $this->rgbarrToHex($tag->getPastelColor());
			$pointColor      = $this->rgbarrToHex($tag->getLightColor());
			$countDataPoints = array();
			$timeDataPoints  = array();
			// iterate to get totals by day
			for($i = $period;$i <= strtotime("tomorrow");$i += 86400)
			{
				$rem       = array();
				$totalTime = 0;
				foreach($tagTasks as $task)
				{
					if($task->getCloseUnixtime() > $i)
					{
						break;
					}
					else
					{
						$rem[] = $task;
						$totalTime += $task->getUnixtime();
					}
				}
				$countDataPoints[] = array("x" => $i * 1000,"y" => count($rem),"color" => $pointColor);
				$timeDataPoints[]  = array("x" => $i * 1000,"y" => $totalTime,"color" => $pointColor);
				foreach($rem as $task)
				{
					array_shift($tagTasks);
				}
			}

			$countClosedTasksPayload[] = array(
				"type"  => "area",
				"name"  => $tag->getName(),
				"data"  => $countDataPoints,
				"color" => $tagColor,
			);
			$timeClosedTasksPayload[]  = array(
				"type"  => "area",
				"name"  => $tag->getName(),
				"data"  => $timeDataPoints,
				"color" => $tagColor,
			);
		}

		return $this->finalize(
			array(
				"user"                    => self::getCurrentUser(),

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/interval.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Edit Interval{% endblock %}
{% block body %}
    {{ form(form) }}
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/intervallist.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Interval List{% endblock %}
{% block body %}
    <div class="floatbox">
        {% include 'TimeTrackerBundle:Default:tag_filters.html.twig' %}
    </div>
    <table cellpadding="0" cellspacing="0">
        {% for interval in intervals %}
            <tr>
                <td>
                    <a href="task?id={{ interval.task.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">{{ interval.task.name }}</a>
                </td>
                <td><a
                            {% if interval.stop is not null %}
                                href="interval?id={{ interval.id }}"
                            {% endif %}
                            >
                        {{ interval.start | date(user.shortDateFormat~" "~user.timeFormat) }}
                        - {{ interval.stop is null ? "" : interval.stop | date(user.shortDateFormat~" "~user.timeFormat) }}</a>
                    {% if interval.task.status == "RUNNING" and interval.stop is null %}
                        <a class="button action"
                           href="taskstop?id={{ interval.task.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">Stop</a>
                    {% endif %}
                </td>
                <td>{{ interval.time | date(user.dateSpanFormat~" "~user.timeSpanFormat) }}</td>
                <td class="small">{{ interval.note }}</td>
                <td>
                    {% for tag in interval.task.tags %}
                        {% include 'TimeTrackerBundle:Default:tag_widget.html.twig' %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/rawlist.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Raw Text{% endblock %}
{% block body %}
    <div>
<pre>{% for task in tasks %}{% for tag in task.tags %}[{{ tag.name }}] {% endfor %}{{ task.name }} - {{ task.desc }}
{% endfor %}</pre>
    </div>
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/report.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Reports{% endblock %}
{% block body %}
    <div id="chart-countClosedTasks"></div>
    <div id="chart-timeClosedTasks"></div>
    <table cellpadding="0" cellspacing="0">
        {% for task in closedInPeriod %}
            <tr class="task">
                <td><a href="task?id={{ task.id }}">{{ task.name }}</a></td>
                <td class="small">{{ task.desc[:150] }}{% if task.desc|length >150 %}...{% endif %}</td>
                {% if task.lastInterval is not empty %}
                    <td class="small">{{ task.time|date("%d\n%H%I%S")|nl2br }}</td>
                {% else %}
                    <td colspan="1"></td>
                {% endif %}
                <td>
                    {% for tag in task.tags %}
                        {% include 'TimeTrackerBundle:Default:tag_widget.html.twig' %}
                    {% endfor %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}
{% block javascripts %}
    {% javascripts
    '@TimeTrackerBundle/Resources/public/js/highcharts.js'
    '@TimeTrackerBundle/Resources/public/js/charts.js' %}
    <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
    <script type="text/javascript">
        $(function () {
            $("#chart-countClosedTasks").highcharts(countClosedTasks({{ countClosedTasksPayload|json_encode|raw }}))
        });
        $(function () {
            $("#chart-timeClosedTasks").highcharts(timeClosedTasks({{ timeClosedTasksPayload|json_encode|raw }}))
        });
    </script>
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/tag.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Edit Tag{% endblock %}
{% block body %}
    {{ form(form) }}
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/tagGroup.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Edit Group{% endblock %}
{% block body %}

    {{ form(form) }}
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/tag_widget.html.twig
<a class="tag lozenge {{ tag_inverted is defined and tag_inverted ? "inverted":"" }} {{ tag.id }}"
   href="{{ tag_url is defined ? tag_url : "tag?id="~tag.id }}" index="{{ tag.id }}"
   title="[{{ tag.group is defined and tag.group is not null ? tag.group.name : "" }}] {{ tag.desc }}">{{ tag.name }}</a>

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/tagstyle.html.twig
<style type="text/css">
    {% for tag in tags %}
    .{{ tag.id }} {
        background: rgb({{ tag.pastelColor | join(',') }}) !important;
        border-color: rgb({{ tag.lightColor | join(',') }}) !important;
        color: rgb({{ tag.mainColor | join(',') }}) !important;
    }

    .{{ tag.id }}:active, .{{ tag.id }}:active:hover, .{{ tag.id }}.inverted, input[type="checkbox"]:checked + label.{{ tag.id }} {
        background: rgb({{ tag.mainColor | join(',') }}) !important;
        border-color: rgb({{ tag.lightColor | join(',') }}) !important;
        color: rgb({{ tag.pastelColor | join(',') }}) !important;
    }

    {% endfor %}
</style>

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/task.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Edit Task{% endblock %}
{% block body %}
    {{ form(form) }}
    {% if obj is defined and obj is not null %}
        <h2>Work</h2>
        {% if obj.status != "CLOSED" and obj.status != "BLOCKED" and obj.status != "RUNNING" %}
            <a class="button action"
               href="taskstart?id={{ obj.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">Start</a>
        {% endif %}
        <table cellpadding="0" cellspacing="0">
            {% for interval in obj.intervals %}
                <tr>
                    <td><a
                                {% if interval.stop is not null %}
                                    href="interval?id={{ interval.id }}"
                                {% endif %}
                                >
                            {{ interval.start | date(user.shortDateFormat~" "~user.timeFormat) }}
                            - {{ interval.stop is null ? "" : interval.stop | date(user.shortDateFormat~" "~user.timeFormat) }}</a>
                        {% if obj.status == "RUNNING" and interval.stop is null %}
                            <a class="button action"
                               href="taskstop?id={{ obj.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">Stop</a>
                        {% endif %}
                    </td>
                    <td>{{ interval.time | date(user.dateSpanFormat~" "~user.timeSpanFormat) }}</td>
                    <td>{{ interval.note }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

src/DeinonychusCowboy/TimeTrackerBundle/Resources/views/Default/tasklist.html.twig
{% extends 'TimeTrackerBundle:Default:managed_base.html.twig' %}
{% block title %}Task List{% endblock %}
{% block body %}
    <div class="floatbox">
        {% include 'TimeTrackerBundle:Default:tag_filters.html.twig' %}
        <div class="toolbar right">
            <a class="button"
               href="tasklist?all{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">Show
                Closed</a>
            <a class="button" href="task{{ filter is defined and filter is not null ? "?filter="~filter : "" }}">Add
                Task</a>
        </div>
    </div>
    <table cellpadding="0" cellspacing="0">
        {% for task in tasks %}
            <tr class="task {{ task.closed?"archived":"" }}">
                <td>
                    <div class="status-{{ task.status | lower }} indicator lozenge"></div>
                </td>
                <td>
                    <a href="task?id={{ task.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">{{ task.name }}</a>
                </td>
                <td class="small">{{ task.desc[:150] }}{% if task.desc|length >150 %}...{% endif %}</td>
                {% if task.lastInterval is not empty %}
                    <td class="small">{{ task.lastInterval.start|date(user.shortDateFormat~"\n"~user.timeFormat)|nl2br }}</td>
                    <td class="small">{{ task.lastInterval.stop is empty ? "" : task.lastInterval.stop|date(user.shortDateFormat~"\n"~user.timeFormat)|nl2br }}</td>
                    <td class="small">{{ task.time|date(user.dateSpanFormat~"\n"~user.timeSpanFormat)|nl2br }}</td>
                {% else %}
                    <td colspan="3"></td>
                {% endif %}
                <td>
                    {% for tag in task.tags %}
                        {% include 'TimeTrackerBundle:Default:tag_widget.html.twig' %}
                    {% endfor %}
                </td>
                <td>
                    {% if task.status == "RUNNING" %}
                        <a class="button action"
                           href="taskstop?id={{ task.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">Stop</a>
                    {% elseif task.status != "CLOSED" and task.status != "BLOCKED" %}
                        <a class="button action"
                           href="taskstart?id={{ task.id }}{{ filter is defined and filter is not null ? "&filter="~filter : "" }}">Start</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}